{{- if and .Values.persistence.enabled (gt (len .Values.persistence.volumes) 0) }}
{{- range $k, $v := $.Values.persistence.volumes }}
{{- if not $v.existingPersistence }}
{{- $markName := include "mark.fullname" $ }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $v.name | default $markName }}
  # namespace: {{ $.Release.Namespace }}
{{- with $v.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ $markName }}
    {{- include "mark.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $v.accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      {{- $storage := default "10Gi" $v.size }}
      storage: {{ $storage | quote }}
{{- if $v.storageClass }}
{{- if (eq "-" $v.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ $v.storageClass | quote }}
  volumeMode: {{ $v.volumeMode | default "Filesystem"}}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
