{{- if and .Values.persistence.enabled (gt (len .Values.persistence.volumes) 0) }}
{{- range $k, $v := $.Values.persistence.volumes }}
{{- if and (not $v.existingPersistence) ($v.pv) }}
{{- $markName := include "mark.fullname" $ }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" $v.name | default $markName }}
{{- with $v.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ $markName }}
    {{- include "mark.labels" $ | nindent 4 }}

spec:
  capacity:
    storage: {{ $v.pv.capacity }}
  accessModes:
    - {{ $v.pv.accessModes }}

  {{- if $v.pv.hostPath }}
  hostPath:
    path: {{ $v.pv.hostPath }}
    type: {{ $v.pv.hostPathType }}
  {{- end }}
  {{- if $v.pv.nfs }}
  nfs:
    path: {{ $v.pv.nfs.path }}
    server: {{ $v.pv.nfs.server }}
  {{- end }}
  {{- if $v.pv.awsElasticBlockStore }}
  awsElasticBlockStore:
    volumeID: {{ $v.pv.awsElasticBlockStore.volumeID }}
    fsType: {{ $v.pv.awsElasticBlockStore.fsType }}
  {{- end }}
  {{- if $v.pv.azureDisk }}
  azureDisk:
    diskName: {{ $v.pv.azureDisk.diskName }}
    diskURI: {{ $v.pv.azureDisk.diskURI }}
    cachingMode: {{ $v.pv.azureDisk.cachingMode }}
    kind: {{ $v.pv.azureDisk.kind }}
    fsType: {{ $v.pv.azureDisk.fsType }}
  {{- end }}
  {{- if $v.pv.azureFile }}
  azureFile:
    secretName: {{ $v.pv.azureFile.secretName }}
    shareName: {{ $v.pv.azureFile.shareName }}
    readOnly: {{ $v.pv.azureFile.readOnly }}
  {{- end }}
  {{- if $v.pv.gcePersistentDisk }}
  gcePersistentDisk:
    pdName: {{ $v.pv.gcePersistentDisk.pdName }}
    fsType: {{ $v.pv.gcePersistentDisk.fsType }}
    partition: {{ $v.pv.gcePersistentDisk.partition }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
