{{- if and .Values.secrets }}
{{- range $k, $v := $.Values.secrets }}
{{- if or $v.secretData $v.secretFiles $v.stringData $v.dockerconfigjson }}
{{- $fullName := include "mark.fullname" $ }}
apiVersion: v1
kind: Secret
metadata:
  {{- if $v.dockerconfigjson }}
  name: gitlab-registry
  {{- else}}
  name: {{ $v.name | default (printf "%s-secret" $fullName)}}
  {{- end}}
  labels:
  {{- if  $v.labels }}
  {{ toYaml $v.labels | nindent 4 }}
  {{- end}}
  {{- include "mark.labels" $ | nindent 4 }}

{{- if $v.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- else}}
type: {{ $v.type | default "Opaque" }}
{{- end}}

data:
{{- range $key, $value := $v.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key, $value := $v.secretFiles }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- if $v.dockerconfigjson }}
  .dockerconfigjson: {{ $v.dockerconfigjson | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
